namespace JsRt;

public enum JsErrorCode
{
    JsNoError = 0,
    JsErrorCategoryUsage = 0x10000,
    JsErrorInvalidArgument,
    JsErrorNullArgument,
    JsErrorNoCurrentContext,
    JsErrorInExceptionState,
    JsErrorNotImplemented,
    JsErrorWrongThread,
    JsErrorRuntimeInUse,
    JsErrorBadSerializedScript,
    JsErrorInDisabledState,
    JsErrorCannotDisableExecution,
    JsErrorHeapEnumInProgress,
    JsErrorArgumentNotObject,
    JsErrorInProfileCallback,
    JsErrorInThreadServiceCallback,
    JsErrorCannotSerializeDebugScript,
    JsErrorAlreadyDebuggingContext,
    JsErrorAlreadyProfilingContext,
    JsErrorIdleNotEnabled,
    JsCannotSetProjectionEnqueueCallback,
    JsErrorCannotStartProjection,
    JsErrorInObjectBeforeCollectCallback,
    JsErrorObjectNotInspectable,
    JsErrorPropertyNotSymbol,
    JsErrorPropertyNotString,
    JsErrorCategoryEngine = 0x20000,
    JsErrorOutOfMemory,
    JsErrorCategoryScript = 0x30000,
    JsErrorScriptException,
    JsErrorScriptCompile,
    JsErrorScriptTerminated,
    JsErrorScriptEvalDisabled,
    JsErrorCategoryFatal = 0x40000,
    JsErrorFatal,
    JsErrorWrongRuntime,
}
